using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Globalization;

namespace oed
{
    public static class CompletionData
    {
     static string[] data = new[]
            {
"el Abenaki",
"el Afrikaans",
"el Afro-Asiatic",
"el Akan",
"el Akkadian",
"el Albanian",
"el Algic",
"el Algonquian",
"el Algonquin",
"el Altaic",
"el Amharic",
"el Arabic",
"el Aramaic",
"el Arawakan",
"el Armenian",
"el Ashanti",
"el Assamese",
"el Assyrian",
"el Athapaskan",
"el Atlantic",
"el Atlantic-Congo",
"el Australian Aboriginal",
"el Austroasiatic",
"el Austronesian",
"el Avestan",
"el Balinese",
"el Balto-Slavic",
"el Bantu",
"el Basque",
"el Bengali",
"el Benue-Congo",
"el Beothuk",
"el Berber",
"el Blackfoot",
"el Breton",
"el Brittonic",
"el Bulgarian",
"el Burmese",
"el Caddoan",
"el Canadian French",
"el Cariban",
"el Catalan",
"el Celtic",
"el Chadic",
"el Chichewa",
"el Chinese",
"el Chinook Jargon",
"el Chinookan",
"el Choctaw",
"el Church Slavonic",
"el Coptic",
"el Cornish",
"el Corsican",
"el Cree",
"el Creek",
"el Creoles and pidgins",
"el Croatian",
"el Cushitic",
"el Czech",
"el Danish",
"el Dharuk",
"el Dinka",
"el Diyari",
"el Dravidian",
"el Dutch",
"el East Germanic",
"el East Slavonic",
"el Eastern Romance",
"el Egyptian",
"el English",
"el Eskimo-Aleut",
"el Ethiopic",
"el Fante",
"el Faroese",
"el Fijian",
"el Finnish",
"el Flemish",
"el Franco-ProvenÃ§al",
"el Frankish",
"el French",
"el French Creole",
"el Frisian",
"el Fula",
"el Gaelic",
"el Galibi",
"el Gallo-Italic",
"el Gallo-Romance",
"el Gaulish",
"el Gbe",
"el Georgian",
"el German",
"el Germanic",
"el Goidelic",
"el Gothic",
"el Greek",
"el Greenlandic",
"el Gujarati",
"el Haida",
"el Haitian Creole",
"el Hausa",
"el Hawaiian",
"el Hebrew",
"el Hindi",
"el Hittite",
"el Hokan",
"el Hopi",
"el Hungarian",
"el Iban",
"el Ibero-Romance",
"el Icelandic",
"el Igbo",
"el Indo-Aryan",
"el Indo-European",
"el Indo-Iranian",
"el Indonesian",
"el Inuit",
"el Inupiaq",
"el Iranian",
"el Irish",
"el Iroquoian",
"el Isicamtho",
"el Italian",
"el Italic",
"el Italo-Western",
"el Jamaican Creole",
"el Japanese",
"el Javanese",
"el Jivaro",
"el Kamilaroi",
"el Kannada",
"el Karok",
"el Kashmiri",
"el Khmer",
"el Khoekhoe",
"el Khoisan",
"el Kimbundu",
"el Kongo",
"el Korean",
"el Kurdish",
"el Kwa",
"el Latin",
"el Law French",
"el Lenape",
"el Low German",
"el Luganda",
"el Macusi",
"el Malagasy",
"el Malay",
"el Malayalam",
"el Maliseet-Passamaquoddy",
"el Maltese",
"el Malto",
"el Mande",
"el Manding",
"el Manx",
"el Maori",
"el Mapuche",
"el Marathi",
"el Marquesan",
"el Masai",
"el Massachusett",
"el Mayan",
"el Melanesian pidgins",
"el Mende",
"el Mon",
"el Mon-Khmer",
"el Mongolian",
"el MoorÃ©",
"el Munda",
"el Munsee",
"el Muskogean",
"el Na-Dene",
"el Nahuatl",
"el Nama",
"el Narragansett",
"el Navajo",
"el Ndebele",
"el Nepali",
"el Nguni",
"el Niger-Congo",
"el Nilo-Saharan",
"el Nilotic",
"el Nootka",
"el Norman",
"el Norn",
"el North American languages",
"el North Germanic",
"el Norwegian",
"el Nuclear Na-Dene",
"el Nyamwezi",
"el Nyanja",
"el Nyungar",
"el Occitan",
"el Ojibwa",
"el Old Norse",
"el Old Saxon",
"el Osco-Umbrian",
"el Other sources",
"el Pali",
"el Panjabi",
"el Pashto",
"el Penutian",
"el Persian",
"el Picard",
"el Pima-Papago",
"el Plateau Penutian",
"el Polish",
"el Polynesian",
"el Portuguese",
"el Powhatan",
"el Quechua",
"el Rajasthani",
"el Romance",
"el Romani",
"el Romanian",
"el Russian",
"el Salishan",
"el Samoan",
"el Sanskrit",
"el Sardinian",
"el Scandinavian",
"el Scottish Gaelic",
"el Semitic",
"el Senegambian",
"el Serbian",
"el Serbian and Croatian",
"el Setswana",
"el Shelta",
"el Shona",
"el Sinhala",
"el Sino-Tibetan",
"el Siouan",
"el Sioux",
"el Slavonic",
"el Slovene",
"el Somali",
"el Sotho",
"el Sotho-Tswana",
"el South Caucasian",
"el South Slavonic",
"el Southern Romance",
"el Spanish",
"el Sranan",
"el Sumerian",
"el Swahili",
"el Swedish",
"el Syriac",
"el Tagalog",
"el Tahitian",
"el Tamil",
"el Telugu",
"el Thai",
"el Tibetan",
"el Tibeto-Burman",
"el Tlingit",
"el Tongan",
"el Tungusic",
"el Tupi-Guarani",
"el Turki",
"el Turkic",
"el Turkish",
"el Twi",
"el Ukrainian",
"el Unami Delaware",
"el Uralic",
"el Urdu",
"el Uto-Aztecan",
"el Venda",
"el Vietnamese",
"el Wakashan",
"el Walloon",
"el Washo",
"el Welsh",
"el West Germanic",
"el West Slavonic",
"el Wiradhuri",
"el Wiradhuric",
"el Wiyot",
"el Wolof",
"el Xhosa",
"el Yanomamo",
"el Yiddish",
"el Yokuts",
"el Yoruba",
"el Yupik",
"el Zulu",
"el acronym",
"el error",
"el imitative",
"el initialism",
"el invented",
"el origin uncertain",
"el personal name",
"el place name",
            }; 


    }

}