
namespace oed
{
    public static class CompletionData
    {
    public static string[] PartsOfSpeech = new[]
    {
    "CC",
    "CD",
    "DT",
    "EX",
    "FW",
    "IN",
    "JJ",
    "JJR",
    "JJS",
    "MD",
    "NN",
    "NNP",
    "NNS",
    "PDT",
    "POS",
    "PRP",
    "PRP$",
    "RB",
    "RBR",
    "RBS",
    "RP",
    "SYM",
    "TO",
    "UH",
    "VB",
    "VBD",
    "VBG",
    "VBN",
    "VBZ",
    "WDT",
    "WP",
    "WP$",
    "WRB"
    };

     public static string[] ELanguageData = new[]
            {
                "Abenaki",
                "Afrikaans",
                "Afro-Asiatic",
                "Akan",
                "Akkadian",
                "Albanian",
                "Algic",
                "Algonquian",
                "Algonquin",
                "Altaic",
                "Amharic",
                "Arabic",
                "Aramaic",
                "Arawakan",
                "Armenian",
                "Ashanti",
                "Assamese",
                "Assyrian",
                "Athapaskan",
                "Atlantic",
                "Atlantic-Congo",
                "Australian Aboriginal",
                "Austroasiatic",
                "Austronesian",
                "Avestan",
                "Balinese",
                "Balto-Slavic",
                "Bantu",
                "Basque",
                "Bengali",
                "Benue-Congo",
                "Beothuk",
                "Berber",
                "Blackfoot",
                "Breton",
                "Brittonic",
                "Bulgarian",
                "Burmese",
                "Caddoan",
                "Canadian French",
                "Cariban",
                "Catalan",
                "Celtic",
                "Chadic",
                "Chichewa",
                "Chinese",
                "Chinook Jargon",
                "Chinookan",
                "Choctaw",
                "Church Slavonic",
                "Coptic",
                "Cornish",
                "Corsican",
                "Cree",
                "Creek",
                "Creoles and pidgins",
                "Croatian",
                "Cushitic",
                "Czech",
                "Danish",
                "Dharuk",
                "Dinka",
                "Diyari",
                "Dravidian",
                "Dutch",
                "East Germanic",
                "East Slavonic",
                "Eastern Romance",
                "Egyptian",
                "English",
                "Eskimo-Aleut",
                "Ethiopic",
                "Fante",
                "Faroese",
                "Fijian",
                "Finnish",
                "Flemish",
                "Franco-ProvenÃ§al",
                "Frankish",
                "French",
                "French Creole",
                "Frisian",
                "Fula",
                "Gaelic",
                "Galibi",
                "Gallo-Italic",
                "Gallo-Romance",
                "Gaulish",
                "Gbe",
                "Georgian",
                "German",
                "Germanic",
                "Goidelic",
                "Gothic",
                "Greek",
                "Greenlandic",
                "Gujarati",
                "Haida",
                "Haitian Creole",
                "Hausa",
                "Hawaiian",
                "Hebrew",
                "Hindi",
                "Hittite",
                "Hokan",
                "Hopi",
                "Hungarian",
                "Iban",
                "Ibero-Romance",
                "Icelandic",
                "Igbo",
                "Indo-Aryan",
                "Indo-European",
                "Indo-Iranian",
                "Indonesian",
                "Inuit",
                "Inupiaq",
                "Iranian",
                "Irish",
                "Iroquoian",
                "Isicamtho",
                "Italian",
                "Italic",
                "Italo-Western",
                "Jamaican Creole",
                "Japanese",
                "Javanese",
                "Jivaro",
                "Kamilaroi",
                "Kannada",
                "Karok",
                "Kashmiri",
                "Khmer",
                "Khoekhoe",
                "Khoisan",
                "Kimbundu",
                "Kongo",
                "Korean",
                "Kurdish",
                "Kwa",
                "Latin",
                "Law French",
                "Lenape",
                "Low German",
                "Luganda",
                "Macusi",
                "Malagasy",
                "Malay",
                "Malayalam",
                "Maliseet-Passamaquoddy",
                "Maltese",
                "Malto",
                "Mande",
                "Manding",
                "Manx",
                "Maori",
                "Mapuche",
                "Marathi",
                "Marquesan",
                "Masai",
                "Massachusett",
                "Mayan",
                "Melanesian pidgins",
                "Mende",
                "Mon",
                "Mon-Khmer",
                "Mongolian",
                "MoorÃ©",
                "Munda",
                "Munsee",
                "Muskogean",
                "Na-Dene",
                "Nahuatl",
                "Nama",
                "Narragansett",
                "Navajo",
                "Ndebele",
                "Nepali",
                "Nguni",
                "Niger-Congo",
                "Nilo-Saharan",
                "Nilotic",
                "Nootka",
                "Norman",
                "Norn",
                "North American languages",
                "North Germanic",
                "Norwegian",
                "Nuclear Na-Dene",
                "Nyamwezi",
                "Nyanja",
                "Nyungar",
                "Occitan",
                "Ojibwa",
                "Old Norse",
                "Old Saxon",
                "Osco-Umbrian",
                "Other sources",
                "Pali",
                "Panjabi",
                "Pashto",
                "Penutian",
                "Persian",
                "Picard",
                "Pima-Papago",
                "Plateau Penutian",
                "Polish",
                "Polynesian",
                "Portuguese",
                "Powhatan",
                "Quechua",
                "Rajasthani",
                "Romance",
                "Romani",
                "Romanian",
                "Russian",
                "Salishan",
                "Samoan",
                "Sanskrit",
                "Sardinian",
                "Scandinavian",
                "Scottish Gaelic",
                "Semitic",
                "Senegambian",
                "Serbian",
                "Serbian and Croatian",
                "Setswana",
                "Shelta",
                "Shona",
                "Sinhala",
                "Sino-Tibetan",
                "Siouan",
                "Sioux",
                "Slavonic",
                "Slovene",
                "Somali",
                "Sotho",
                "Sotho-Tswana",
                "South Caucasian",
                "South Slavonic",
                "Southern Romance",
                "Spanish",
                "Sranan",
                "Sumerian",
                "Swahili",
                "Swedish",
                "Syriac",
                "Tagalog",
                "Tahitian",
                "Tamil",
                "Telugu",
                "Thai",
                "Tibetan",
                "Tibeto-Burman",
                "Tlingit",
                "Tongan",
                "Tungusic",
                "Tupi-Guarani",
                "Turki",
                "Turkic",
                "Turkish",
                "Twi",
                "Ukrainian",
                "Unami Delaware",
                "Uralic",
                "Urdu",
                "Uto-Aztecan",
                "Venda",
                "Vietnamese",
                "Wakashan",
                "Walloon",
                "Washo",
                "Welsh",
                "West Germanic",
                "West Slavonic",
                "Wiradhuri",
                "Wiradhuric",
                "Wiyot",
                "Wolof",
                "Xhosa",
                "Yanomamo",
                "Yiddish",
                "Yokuts",
                "Yoruba",
                "Yupik",
                "Zulu",
                "acronym",
                "error",
                "imitative",
                "initialism",
                "invented",
                "origin uncertain",
                "personal name",
                "place name",
            }; 

    public static string[] ETypesData = new[] {
        "compound",
        "derivative",
        "conversion",
        "blend",
        "shortening",
        "backformation",
        "initialism",
        "acronym",
        "variant",
        "arbitrary",
        "imitative",
        "borrowing",
        "borrowingHybrid",
        "inherited",
        "properName",
        "properNameHybrid",
        "unknown",
        "uncertain"
    };

    public static string[] Usage = new[] {
        "archaic",
        "allusive",
        "colloquial and slang",
        "coarse slang",
        "cant",
        "rhyming slang",
        "school slang",
        "university slang",
        "derogatory",
        "disused",
        "euphemistic",
        "historical",
        "humorous",
        "ironic",
        "irregular",
        "poetic and literary",
        "rare",
        "regional"
    };

    public static string[] Regions = new[] {
        "New Zealand",
        "Britain and Ireland",
        "Britain",
        "England",
        "Africa",
        "East Africa",
        "South Africa",
        "West Africa",
        "Australasia",
        "Australia",
        "Northern England",
        "North-West England",
        "North-East England",
        "Yorkshire",
        "Southern England",
        "South-East England",
        "South-West England",
        "London",
        "Eastern England",
        "English Midlands",
        "Scotland",
        "Northern Scotland",
        "Southern Scotland",
        "Shetland",
        "Orkney",
        "Wales",
        "Isle of Man",
        "Ireland",
        "Northern Ireland",
        "Caribbean",
        "Jamaica",
        "India",
        "North America",
        "United States",
        "Northern United States",
        "Southern United States",
        "Eastern United States",
        "Western United States",
        "United States Midland",
        "African-American",
        "Canada",
        "Hawaii",
        "South-East Asia"
    };

    public static string[] Topics = new[] {
       "Heraldry",
"History",
"Agriculture and Horticulture",
"Agriculture",
"Sheep-shearing",
"Hop-growing",
"Forestry",
"Horticulture",
"Bee-keeping",
"Arts",
"Visual Arts",
"Painting and Drawing",
"Painting",
"Drawing",
"Sculpture",
"Printmaking",
"Engraving and Etching",
"Literature",
"Prosody",
"Rhetoric",
"Literary and Textual Criticism",
"Science Fiction",
"Performing Arts",
"Music",
"Popular Music",
"Jazz",
"World Music",
"Organ-playing",
"Bell-ringing",
"Theatre",
"Dance",
"Ballet",
"Conjuring",
"Film",
"Decorative Arts",
"Enamelling",
"Gilding",
"Handwriting and Calligraphy",
"Consumables",
"Food and Cooking",
"Baking",
"Cheese",
"Drink",
"Wine",
"Beer",
"Cider",
"Distilling",
"Malting",
"Tobacco",
"Crafts and Trades",
"Woodworking",
"Textiles",
"Weaving",
"Spinning",
"Knitting",
"Needlework",
"Lace",
"Silk",
"Wool",
"Calico-printing",
"Printing and Typography",
"Bookbinding",
"Clocks and Watches",
"Coins and Banknotes",
"Postage Stamps",
"Leather-making",
"Costume",
"Tailoring",
"Dressmaking",
"Hats",
"Gloves",
"Shoes",
"Jewellery",
"Cosmetics",
"Perfumery",
"Rope-making",
"Soap-making",
"Dyeing",
"Carriage-building",
"Fireworks",
"Metalwork",
"Coopering",
"Gem-cutting",
"Locksmithing",
"Ceramics",
"Basket-making",
"Fur Trade",
"Bleaching",
"Hairdressing",
"Drug use",
"Economics and Commerce",
"Economics",
"Finance",
"Banking",
"Stock Market",
"Insurance",
"Accounting",
"Education",
"University",
"Oxford University",
"Cambridge University",
"Archaeology",
"Palaeography",
"Ancient History",
"Classical History",
"Roman History",
"Ancient Greek History",
"Ancient Egyptian History",
"Medieval History",
"Language",
"Linguistics",
"Grammar",
"Phonetics",
"Philology",
"Cryptography",
"Law",
"British Law",
"English Law",
"Scottish Law",
"North American Law",
"United States Law",
"Ecclesiastical Law",
"Medieval Law",
"Roman Law",
"Manufacturing and Industry",
"Manufacturing",
"Metal Industry",
"Papermaking",
"Glass-making",
"Oil and Gas Industry",
"Mining",
"Coal Mining",
"Gold-mining",
"Quarrying",
"Commercial Fishing",
"Whaling",
"Civil Engineering",
"Building",
"Architecture",
"Church Architecture",
"Plastering",
"Plumbing",
"Masonry",
"Brickmaking",
"Bricklaying",
"Glazing",
"Roofing",
"Thatching",
"Salt-making",
"Sugar Industry",
"Publishing and the Book Trade",
"Fish",
"Publishing",
"Journalism",
"Logging",
"Military",
"Fortification",
"Air Force",
"Weaponry",
"Gunnery and Firearms",
"Armour",
"Espionage",
"Organizations",
"Scouting and Guiding",
"Freemasonry",
"Philosophy",
"Logic",
"Politics",
"United States Politics",
"British Politics",
"Parliament",
"Religion and Belief",
"Religion",
"Christianity",
"Liturgical",
"Ecclesiastical",
"Anglican Church",
"Scottish Church",
"Magnetism",
"Roman Catholic Church",
"Orthodox Church",
"Quakerism",
"Methodism",
"Buddhism",
"Sikhism",
"Jainism",
"Hinduism",
"Islam",
"Judaism",
"Shinto",
"Belief systems and practices",
"Spiritualism",
"Yoga",
"Astrology",
"Palmistry",
"Parapsychology",
"Occult",
"Mythology",
"Classical Mythology",
"Sciences",
"Life Sciences",
"Animals",
"Birds",
"Invertebrates",
"Insects",
"Shells and Shellfish",
"Plants",
"Fungi",
"Plant Pathology",
"Plant Physiology",
"Palaeontology",
"Microbiology",
"Bacteria",
"Viruses",
"Ecology",
"Genetics",
"Cell Biology",
"Taxonomy",
"Physical Sciences",
"Chemistry",
"Organic Chemistry",
"Crystals",
"Metals",
"Alchemy",
"Physics",
"Particle Physics",
"Nuclear Physics",
"Optics",
"Dynamics",
"Spectroscopy",
"Acoustics",
"Earth Sciences",
"Minerals",
"Geology",
"Soil Science",
"Geography",
"Physical Geography",
"Oceanography",
"Weather",
"Cartography",
"Surveying",
"Astronomy",
"Mathematics",
"Geometry",
"Statistics",
"Medicine",
"Anatomy",
"Physiology",
"Pathology",
"Pharmacology",
"Surgery",
"Immunology",
"Ophthalmology",
"Dentistry",
"Obstetrics",
"Embryology",
"Neurology",
"Radiology",
"Massage",
"Phrenology",
"Psychology",
"Psychiatry",
"Psychoanalysis",
"Alternative Medicine",
"Herbalism",
"Veterinary Medicine",
"Social Sciences",
"Sociology",
"Cultural Anthropology",
"Sport and Leisure",
"Sport",
"Football",
"American Football",
"Rugby Football",
"Association Football",
"Australian Rules Football",
"Cricket",
"Baseball",
"Golf",
"Basketball",
"Hockey",
"Racket Sports",
"Real Tennis",
"Tennis",
"Badminton",
"Squash",
"Lacrosse",
"Bowls",
"Bowling",
"Athletics",
"Gymnastics",
"Motor Racing",
"Billiards, Pool, and Snooker",
"Winter Sports",
"Skiing",
"Skating",
"Ice Hockey",
"Curling",
"Cycling",
"Boxing",
"Wrestling",
"Martial Arts",
"Sumo",
"Fencing",
"Swimming",
"Diving",
"Archery",
"Climbing",
"Caving",
"Skateboarding",
"Weightlifting",
"Parachuting",
"Water Sports",
"Rowing",
"Surfing",
"Blood Sports",
"Bullfighting",
"Cockfighting",
"Horses and Riding",
"Horse Racing",
"Polo",
"Farriery",
"Saddles and Harness",
"Hunting, Fishing, and Shooting",
"Angling",
"Hunting",
"Shooting",
"Hawking and Falconry",
"Games",
"Board Games",
"Chess",
"Backgammon",
"Draughts",
"Mah-jong",
"Cards",
"Bridge",
"Whist",
"Poker",
"Euchre",
"Faro",
"Cribbage",
"Piquet",
"Croquet",
"Dominoes",
"Darts",
"Quoits",
"Gambling",
"Dice",
"Betting",
"Roulette",
"Technology",
"Electrical",
"Electrical Engineering",
"Electronics",
"Engineering",
"Mechanics",
"Steam Engines",
"Hydraulics",
"Telecommunications",
"Broadcasting",
"Television",
"Radio",
"Telephony",
"Telegraphy",
"Recording",
"Sound Recording",
"Video Recording",
"Photography",
"Radar",
"Computing",
"Measurement",
"Transport",
"Nautical",
"Shipbuilding",
"Navy",
"Sailing",
"Aviation",
"Motoring",
"Motorcycling",
"Astronautics",
"Railways",
"Inland Waterways"
    };
}
}